### ISSUE TITLE
LayerSkip Code Checklist

### ISSUE THREAD

**Issue by mostafaelhoushi** [facebookresearch/LayerSkip#1]
Here is a list of tasks and ideas... they are not all necessary. Also not sure after which task to open source... we can opensource now.

- [x] Use HuggingFace datasets for CNN/DM, XSUM, HumanEval
- [x] Make num_shots, seeds become arguments
- [x] Add License
- [x] #7
- [x] Sweep on optimal early_exit_layer and num_speculations
- [x] Get correctness.py to Work
- [x] Implement sampling with temperature
- [ ] Address minor TODO comments in code
- [x] Refactor arguments across scripts
- [x] Refactor generate.py
- [x] #6
- [x] Implement Text Streaming for Output
- [x] Implement Text Correction Streaming for Self-Speculation
- [ ] Implement training using Early Exit Loss
- [ ] Implement training using Layer Dropout

Cc @AkshatSh
